@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NzI3OTU3ODF9.Tn2-QJJ9EualBD6NobvMGDMgllkChsMU1B7f7hx3vPU
@admin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NzI3OTAxOTV9.ByIwE3nPY9x-bV7xDjhMe4RP88SOhPDGBJwE5FyAfL8

#### USERS #### 
### Users index 
GET http://localhost:3000/users.json

### Users show
GET http://localhost:3000/users/1.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Callam the Clueless",
  "email": "c@example.com",
  "password": "password",
  "password_confirmation": "password",
  "image_url": "NO PIC!"
}

### Users destroy
DELETE http://localhost:3000/users/5.json
Authorization: Bearer {{admin}}

#### SESSIONS #### 
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "g@example.com",
  "password": "password"
}

#### TRAILS #### 
### Trails index
GET http://localhost:3000/trails.json

### Trails show 
GET http://localhost:3000/trails/1.json

### Trails create
POST http://localhost:3000/trails.json
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "name": "TESTY TEST",
  "description": "Loopy",
  "length": 3,
  "difficulty": "Easy peasy",
  "image_url": "NO PIC!"
}

### Trails update
PATCH http://localhost:3000/trails/5.json
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "image_url": "https://imgur.com/ZNycI0r"
}

### Trails destroy
DELETE http://localhost:3000/trails/7.json
Authorization: Bearer {{admin}}

#### FAST FACTS #### 
### Fast Facts index
GET http://localhost:3000/fast_facts.json

### Fast Facts show 
GET http://localhost:3000/fast_facts/1.json

### Fast Facts create
POST http://localhost:3000/fast_facts.json
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "general": "TESTY TEST",
  "nearby_landmarks": "A MOUNTAIN",
  "lake_info": "NO LAKES!",
  "backcountry_zones": "NO ZONES!",
  "ecological_zones": "Riparian",
  "trail_id": 1
}

### Fast Facts update
PATCH http://localhost:3000/fast_facts/4.json
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "lake_info": "NO LAKE!"
}

### Fast Facts destroy
DELETE http://localhost:3000/fast_facts/4.json
Authorization: Bearer {{admin}}

#### CONDIS #### 
### Conditions index
GET http://localhost:3000/conditions.json

### Conditions show 
GET http://localhost:3000/conditions/1.json

### Conditions create
POST http://localhost:3000/conditions.json
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "trail_condition": "TESTY TEST",
  "temp": 0,
  "forecast": "SUNS OUT GUNS OUT!",
  "sunrise_time": 7,
  "sunset_time": 9,
  "trail_id": 1
}

### Conditions update
PATCH http://localhost:3000/conditions/3.json
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "sunrise_time": 8,
  "sunset_time": 4
}

### Conditions destroy
DELETE http://localhost:3000/conditions/6.json
Authorization: Bearer {{admin}}


#### Hike Schedule #### 
### Hike Schedule index
GET http://localhost:3000/hike_schedules.json
Authorization: Bearer {{jwt}}

### Hike Schedule create
POST http://localhost:3000/hike_schedules.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "trail_id": 3,
  "date": "2022-09-16"
}

### Hike Schedule destroy
DELETE http://localhost:3000/hike_schedules/6.json
Authorization: Bearer {{jwt}}

