#@jwt = 
@admin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NzI3OTAxOTV9.ByIwE3nPY9x-bV7xDjhMe4RP88SOhPDGBJwE5FyAfL8

#### USERS #### 
### Users index 
GET http://localhost:3000/users.json

### Users show
GET http://localhost:3000/users/1.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Callam the Clueless",
  "email": "c@example.com",
  "password": "password",
  "password_confirmation": "password",
  "image_url": "NO PIC!"
}

### Users destroy
DELETE http://localhost:3000/users/5.json
Authorization: Bearer {{admin}}

#### SESSIONS #### 
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "c@example.com",
  "password": "password"
}

#### TRAILS #### 
### Trails index
GET http://localhost:3000/trails.json

### Trails show 
GET http://localhost:3000/trails/1.json

### Trails create
POST http://localhost:3000/trails.json
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "name": "TESTY TEST",
  "description": "Loopy",
  "length": 3,
  "difficulty": "Easy peasy",
  "image_url": "NO PIC!"
}

### Trails update
PATCH http://localhost:3000/trails/5.json
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "image_url": "https://imgur.com/ZNycI0r"
}

### Trails destroy
DELETE http://localhost:3000/trails/7.json
Authorization: Bearer {{admin}}

